name=M5Unit-LIGHT
version=0.0.1
author=M5Stack
maintainer=M5Stack
sentence=Library for M5Stack UNIT LIGHT using M5UnitUnified
paragraph=Supports BH1750FVI (UnitDLight, SKU:U136 / HatDLight, SKU:U134) for ambient light detection, and LM393 + photoresistor (UnitLight, SKU:U021) for analog light sensing.
category=Device Control
url=https://github.com/m5stack/M5Unit-LIGHT
architectures=esp32
includes=M5UnitUnifiedLIGHT.h
depends=M5UnitUnified,M5Utility,M5HAL
